version: "3.8"
services:
  database:
    image: postgres:13
    container_name: velvet-database
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: velvet-pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: manas@manas.com
      PGADMIN_DEFAULT_PASSWORD: manas
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres: ~
  pgadmin: ~